# Generated by Django 2.1.1 on 2018-09-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
