# Generated by Django 2.1.1 on 2018-10-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_auto_20180925_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hash',
            field=models.CharField(default='temphash', max_length=200),
            preserve_default=False,
        ),
    ]
