# Generated by Django 2.1.1 on 2018-10-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_auto_20181013_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='hash',
        ),
        migrations.AddField(
            model_name='hashes',
            name='hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Word'),
        ),
    ]
