# Generated by Django 2.1.1 on 2018-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_auto_20181013_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='hash',
        ),
        migrations.AddField(
            model_name='hashes',
            name='hash',
            field=models.CharField(default='temphash', max_length=200),
            preserve_default=False,
        ),
    ]
