# Generated by Django 2.1.1 on 2018-10-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_auto_20181013_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='number_of',
            field=models.IntegerField(default=1),
        ),
    ]
