# Generated by Django 2.1.1 on 2018-10-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0009_auto_20181013_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='number_of',
        ),
        migrations.AddField(
            model_name='counter',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.Word'),
        ),
    ]
