# Generated by Django 2.1.1 on 2018-10-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0010_auto_20181013_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='word_count',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='counter.Counter'),
            preserve_default=False,
        ),
    ]
