# Generated by Django 2.1.1 on 2018-10-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0011_auto_20181013_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='counter.Counter'),
        ),
    ]
