# Generated by Django 2.1.1 on 2018-10-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_auto_20181013_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_count',
        ),
        migrations.AddField(
            model_name='word',
            name='number_of',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
